### ISSUE TITLE
Please use VITE v5 instead of MIX

### ISSUE THREAD

**Issue by ebeauchamps** [statamic/starter-kit-doogie-browser#20]
Please see this:
https://github.com/statamic/statamic/pull/66

**Comment by Jubeki** [comment]
@ebeauchamps I think not only should Vite v5 be touched here, but also Tailwindcss v1 -> v3 and maybe Vue 2 -> 3, etc.

So there are multiple dependencies which could be upgraded. So for now, I will not send a Vite 5 PR for this one.

**Comment by duncanmcclean** [comment]
Closed by #21.
